export default{
    path:'/component',
    component:()=>import('@/views/Component'),
    children:[
        {
            path:'layout',
            component:()=>import('@/components/Component/Layout.vue')
        },
        {
            path:'container',
            component:()=>import('@/components/Component/Container.vue')
        },
        {
            path:'icon',
            component:()=>import('@/components/Component/Icon.vue')
        },
        {
            path:'button',
            component:()=>import('@/components/Component/Button.vue')
        },
        {
            path:'link',
            component:()=>import('@/components/Component/Link.vue')
        },
        {
            path:'radio',
            component:()=>import('@/components/Component/Radio.vue')
        },
        {
            path:'checkbox',
            component:()=>import('@/components/Component/Checkbox.vue')
        },
        {
            path:'input',
            component:()=>import('@/components/Component/Input.vue')
        },
        {
            path:'inputnumber',
            component:()=>import('@/components/Component/InputNumber.vue')
        },
        {
            path:'select',
            component:()=>import('@/components/Component/Select.vue')
        },
        {
            path:'cascader',
            component:()=>import('@/components/Component/Cascader.vue')
        },
        {
            path:'switch',
            component:()=>import('@/components/Component/Switch.vue')
        },
        {
            path:'slider',
            component:()=>import('@/components/Component/Slider.vue')
        },
        {
            path:'timepicker',
            component:()=>import('@/components/Component/TimePicker.vue')
        },
        {
            path:'datepicker',
            component:()=>import('@/components/Component/DatePicker.vue')
        },
        {
            path:'datetimepicker',
            component:()=>import('@/components/Component/DateTimePicker.vue')
        },
        {
            path:'upload',
            component:()=>import('@/components/Component/Upload.vue')
        },
        {
            path:'rate',
            component:()=>import('@/components/Component/Rate.vue')
        },
        {
            path:'colorpicker',
            component:()=>import('@/components/Component/ColorPicker.vue')
        },
        {
            path:'transfer',
            component:()=>import('@/components/Component/Transfer.vue')
        },
        {
            path:'form',
            component:()=>import('@/components/Component/Form.vue')
        },
        {
            path:'table',
            component:()=>import('@/components/Component/Table.vue')
        },
        {
            path:'tag',
            component:()=>import('@/components/Component/Tag.vue')
        },
        {
            path:'progress',
            component:()=>import('@/components/Component/Progress.vue')
        },
        {
            path:'tree',
            component:()=>import('@/components/Component/Tree.vue')
        },
        {
            path:'pagination',
            component:()=>import('@/components/Component/Pagination.vue')
        },
        {
            path:'badge',
            component:()=>import('@/components/Component/Badge.vue')
        },
        {
            path:'avatar',
            component:()=>import('@/components/Component/Avatar.vue')
        },
        {
            path:'alert',
            component:()=>import('@/components/Component/Alert.vue')
        },
        {
            path:'loading',
            component:()=>import('@/components/Component/Loading.vue')
        },
        {
            path:'message',
            component:()=>import('@/components/Component/Message.vue')
        },
        {
            path:'messagebox',
            component:()=>import('@/components/Component/MessageBox.vue')
        },
        {
            path:'notification',
            component:()=>import('@/components/Component/Notification.vue')
        },
        {
            path:'navmenu',
            component:()=>import('@/components/Component/NavMenu.vue')
        },
        {
            path:'tabs',
            component:()=>import('@/components/Component/Tabs.vue')
        },
        {
            path:'breadcrumb',
            component:()=>import('@/components/Component/Breadcrumb.vue')
        },
        {
            path:'pageheader',
            component:()=>import('@/components/Component/PageHeader.vue')
        },
        {
            path:'dropdown',
            component:()=>import('@/components/Component/Dropdown.vue')
        },
        {
            path:'steps',
            component:()=>import('@/components/Component/Steps.vue')
        },
        {
            path:'dialog',
            component:()=>import('@/components/Component/Dialog.vue')
        },
        {
            path:'tooltip',
            component:()=>import('@/components/Component/Tooltip.vue')
        },
        {
            path:'popover',
            component:()=>import('@/components/Component/Popover.vue')
        },
        {
            path:'popconfirm',
            component:()=>import('@/components/Component/Popconfirm.vue')
        },
        {
            path:'card',
            component:()=>import('@/components/Component/Card.vue')
        },
        {
            path:'carousel',
            component:()=>import('@/components/Component/Carousel.vue')
        },
        {
            path:'collapse',
            component:()=>import('@/components/Component/Collapse.vue')
        },
        {
            path:'timeline',
            component:()=>import('@/components/Component/Timeline.vue')
        },
        {
            path:'divider',
            component:()=>import('@/components/Component/Divider.vue')
        },
        {
            path:'calendar',
            component:()=>import('@/components/Component/Calendar.vue')
        },
        {
            path:'image',
            component:()=>import('@/components/Component/Image.vue')
        },
        {
            path:'backtop',
            component:()=>import('@/components/Component/Backtop.vue')
        },
        {
            path:'infinitescroll',
            component:()=>import('@/components/Component/InfiniteScroll.vue')
        },
        {
            path:'drawer',
            component:()=>import('@/components/Component/Drawer.vue')
        },
        {
            path:'/component',
            redirect:'layout'
        }
    ]
}